#!/usr/bin/env ruby

require 'find'
require 'fileutils'
require 'reverse_markdown'

SOURCE_DIR = 'docs'
TARGET_DIR = 'markdown'

puts "Create target directory"
FileUtils.mkdir_p(TARGET_DIR)

puts "Copy directores"

FileUtils.cp_r "#{SOURCE_DIR}/images", TARGET_DIR
FileUtils.cp_r "#{SOURCE_DIR}/styles", TARGET_DIR
FileUtils.cp_r "#{SOURCE_DIR}/attachments", TARGET_DIR

puts "Converting files"

md_head = <<-HEAD
---
layout: default
---
HEAD

Find.find(SOURCE_DIR).each do |f|
  if File.extname(f) == '.html'
    md_content = (md_head << ReverseMarkdown.convert(File.read(f)))
    md_name = f.sub(SOURCE_DIR, TARGET_DIR).gsub(/html$/, 'md')
    File.write(md_name, md_content)
    puts "Converted #{f} -> #{md_name}"
  end
end